# -*- coding: utf-8 -*-
"""Least Squares Line Fitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5fbeMC4t_KXsU2BfNeS0uyu0G0Q0M63
"""

import numpy as np
import matplotlib.pyplot as plt

# Generate noisy data
np.random.seed(0)
x = np.linspace(0, 10, 100)
y = 2 * x + 5 + np.random.normal(scale=3, size=x.shape)

# Perform Least Squares Fitting
A = np.vstack([x, np.ones(len(x))]).T
m, c = np.linalg.lstsq(A, y, rcond=None)[0]

print(f"Slope (m): {m}, Intercept (c): {c}")

# Plot the results
plt.scatter(x, y, label='Noisy Data')
plt.plot(x, m * x + c, 'r', label=f'Line: y={m:.2f}x + {c:.2f}')
plt.title('Line Fitting using Least Squares')
plt.legend()
plt.show()