# -*- coding: utf-8 -*-
"""RANSAC Line Fitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1SbyUu89UVEWL68vinM_G9ufnmmMTIl
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import RANSACRegressor

# Generate data with outliers
np.random.seed(42)
x = np.linspace(0, 10, 100)
y = 2 * x + 5 + np.random.normal(scale=2, size=x.shape)
y[::10] += 20  # Add outliers

# Reshape for sklearn
x = x.reshape(-1, 1)

# Apply RANSAC
ransac = RANSACRegressor()
ransac.fit(x, y)
y_pred = ransac.predict(x)

# Display model parameters
print(f"Slope (m): {ransac.estimator_.coef_[0]:.2f}, Intercept (c): {ransac.estimator_.intercept_:.2f}")

# Plot the results
plt.scatter(x, y, color='gray', label='Noisy Data with Outliers')
plt.plot(x, y_pred, color='red', label='RANSAC Line')
plt.title('Robust Line Fitting using RANSAC')
plt.legend()
plt.show()