# -*- coding: utf-8 -*-
"""HOG (Histogram of Oriented Gradients) Descriptor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LOyG9xQMmtm-FgATDjv9yKwbYLH4RyBG
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image
image = cv2.imread('/content/irfan.jpeg')
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Initialize the HOG descriptor
hog = cv2.HOGDescriptor()

# Compute the HOG features and visualization
hog_features = hog.compute(gray_image)

print(f"Feature vector length: {hog_features.shape}")

# Visualize the original image
plt.figure(figsize=(10, 6))
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.title('Original Image')
plt.axis('off')
plt.show()