# -*- coding: utf-8 -*-
"""pedestrians.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ENCwjaOYJZzKQrLCIYpiSOQYPLN_zTVg
"""

import cv2
import matplotlib.pyplot as plt

# Load the image
image = cv2.imread('/content/1696406262988.jpg')
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Initialize the HOG descriptor and set the SVM detector for pedestrian detection
hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

# Detect people in the image
boxes, weights = hog.detectMultiScale(image, winStride=(8, 8), padding=(8, 8), scale=1.05)

# Draw rectangles around detected people
for (x, y, w, h) in boxes:
    cv2.rectangle(image_rgb, (x, y), (x + w, y + h), (255, 0, 0), 3)

# Display the result
plt.figure(figsize=(12, 8))
plt.imshow(image_rgb)
plt.title(f"Pedestrians Detected: {len(boxes)}")
plt.axis('off')
plt.show()