# -*- coding: utf-8 -*-
"""Histogram Equalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kaG3HmPO-HrqvDCxjN-YcSc8F6kLmNZl
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from matplotlib import pyplot as plt

# Load the image in grayscale (required for histogram equalization)
img = cv2.imread('/content/WhatsApp Image 2023-08-29 at 12.16.16 AM.jpeg', cv2.IMREAD_GRAYSCALE)  # Change to your image path

# Check if image loaded successfully
if img is None:
    raise FileNotFoundError("Image not found or invalid path. Please check the file path.")

# 1. Global Histogram Equalization
equalized = cv2.equalizeHist(img)

# 2. CLAHE (Contrast Limited Adaptive Histogram Equalization)
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
clahe_img = clahe.apply(img)

# Display results using cv2_imshow (Colab compatible)
print("Original Image:")
cv2_imshow(img)

print("\nGlobal Histogram Equalization:")
cv2_imshow(equalized)

print("\nCLAHE (Adaptive Equalization):")
cv2_imshow(clahe_img)

# Alternative display using matplotlib
plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
plt.imshow(img, cmap='gray')
plt.title('Original')

plt.subplot(1, 3, 2)
plt.imshow(equalized, cmap='gray')
plt.title('Global Equalization')

plt.subplot(1, 3, 3)
plt.imshow(clahe_img, cmap='gray')
plt.title('CLAHE')
plt.show()

# Save the processed images
cv2.imwrite('original.jpg', img)
cv2.imwrite('equalized.jpg', equalized)
cv2.imwrite('clahe.jpg', clahe_img)