# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_roHTP09IYjbYyjIi2fKDEt-15vn2k_g
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load an image
image = cv2.imread('/content/39052.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# 1. Harris Corner Detection
harris = cv2.cornerHarris(gray, blockSize=2, ksize=3, k=0.04)
image[harris > 0.01 * harris.max()] = [0, 0, 255]

# 2. SIFT Keypoint Detection
sift = cv2.SIFT_create()
keypoints_sift, descriptors = sift.detectAndCompute(gray, None)
sift_image = cv2.drawKeypoints(image, keypoints_sift, None)

# 3. ORB Keypoint Detection
orb = cv2.ORB_create()
keypoints_orb, descriptors = orb.detectAndCompute(gray, None)
orb_image = cv2.drawKeypoints(image, keypoints_orb, None)

# Display the images
plt.figure(figsize=(15, 5))
plt.subplot(131), plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB)), plt.title('Harris Corners')
plt.subplot(132), plt.imshow(cv2.cvtColor(sift_image, cv2.COLOR_BGR2RGB)), plt.title('SIFT Keypoints')
plt.subplot(133), plt.imshow(cv2.cvtColor(orb_image, cv2.COLOR_BGR2RGB)), plt.title('ORB Keypoints')
plt.show()